### PR TITLE
Fix unobserved SocketException (rebase of PR 771, which addresses Issue 770)

### LINKED ISSUE #770: Unobserved exception for socket read operations
We configured FIX client (initiator) and it doesn't crash or log any exceptions but we use Sentry.io for issue detection and it catches a lot of unobserved exceptions like this one:

`System.Net.Sockets.SocketException: Operation canceled
System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
  ?, in void AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
  ?, in int AwaitableSocketAsyncEventArgs.GetResult(short token)
  ?, in async ValueTask<int> SslStream.ReadAsyncInternal<TIOAdapter>(TIOAdapter adapter, Memory<byte> buffer)

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Unable to read data from the transport connection: Operation canceled.)`

### PR DESCRIPTION
**Pull request by gbirchmeier**
resolves #770 (original issue)
resolves #771 (original PR, this is a rebase)

Perform socket read operations according to Task-based asynchronous pattern (TAP) instead of Asynchronous Programming Model (APM)

### CODE REVIEW

**Comment by gbirchmeier** [comment]
@nmandzyk and @Rob-Hague -

I rebased the original PR #771 on latest.  `SocketReader` now has null-analysis turned on, and the compiler is flagging that `_readCancellationTokenSource` can be null at the start of `ReadSome()`.

Looking into that has led me to `DisconnectClient()`, which... well, is there a reason to assign `_readCancelationTokenSource` and `_currentReadTask` to `null` here?  If we left `_readCancellationTokenSource` as a disposed non-null object, the logic wouldn't change, and then we could take the `?` off the var declaration so it would never be null and the warning in `ReadSome()` would go away.

(If I do this, and by some weird chance the var gets referenced after `DisconnectClient()`, then we'd now get a ObjectDisposedException instead of a NullRefException.  Barely a difference functionally, and probably a little easier to diagnose if we need to follow up on it).

(I suspect SocketInitiatorThread might have a similar issue, but I'll enable nullable on this file and clean it up in another commit.)

**Comment by gbirchmeier** [comment]
I've made the nullable fix in the second commit.  Please tell me what you think.

File: QuickFIXn/SocketReader.cs [hunk 1]
```diff
@@ -71,46 +75,44 @@ public void Read()
...
-                _currentReadRequest.AsyncWaitHandle.WaitOne(timeoutMilliseconds);
+                _currentReadTask.Wait(timeoutMilliseconds);
 
-                if (_currentReadRequest.IsCompleted)
-                {
-                    // Make sure to set _currentReadRequest to before retreiving result
-                    // so a new read can be started next time even if an exception is thrown
-                    var request = _currentReadRequest;
-                    _currentReadRequest = null;
+                if (_currentReadTask.IsCompleted) {
```
Comment (Rob-Hague) [inline QuickFIXn/SocketReader.cs:85]: These lines can be

```c#
                if (_currentReadTask.Wait(timeoutMilliseconds)) {
```

File: QuickFIXn/SocketReader.cs [hunk 2]
```diff
@@ -71,46 +75,44 @@ public void Read()
...
+                    // Dispose/nullify currentReadTask *before* retreiving .Result.
+                    //   Accessting .Result can throw an exception, so we need to reset currentReadTask
+                    //   first, to set us up for the next read even if an exception is thrown.
+                    Task<int>? request = _currentReadTask;
+                    _currentReadTask.Dispose();
```
Comment (Rob-Hague) [inline QuickFIXn/SocketReader.cs:90]: Disposing Tasks is [unnecessary](https://devblogs.microsoft.com/pfxteam/do-i-need-to-dispose-of-tasks/). And despite the blog confirming that calling `Result` afterwards should be OK, it still feels a bit strange to call `Result` after `Dispose`. I would suggest removing this line.

File: QuickFIXn/SocketReader.cs [hunk 3]
```diff
@@ -71,46 +75,44 @@ public void Read()
...
+                    _currentReadTask = null;
 
-                    int bytesRead = _stream.EndRead(request);
+                    int bytesRead = request.Result; // (As mentioned above, this can throw an exception!)
```
Comment (Rob-Hague) [inline QuickFIXn/SocketReader.cs:93]: I believe the exceptions will be thrown from `Wait` now, so I don't think the logic to reset `_currentReadTask` to null is going to work anymore in the exceptional case. I think adding `_currentReadTask = null;` in the first line of the catch should sort it.

File: QuickFIXn/SocketReader.cs [hunk 4]
```diff
@@ -71,46 +75,44 @@ public void Read()
...
-                else if (inner is not null)
-                {
+
+                if (inner is not null) {
                     throw inner; //rethrow SocketException part (which we have exception logic for)
                 }
-                else
-                    throw; //rethrow original exception
+
+                throw; //rethrow original exception
```
Comment (Rob-Hague) [inline QuickFIXn/SocketReader.cs:115]: If you care about unwrapping the `AggregateException`, you could do:

```suggestion
                if (ex.InnerExceptions.Count == 1)
                {
                    throw ex.InnerExceptions[0];
                }
                
                throw; //rethrow original exception
```

File: QuickFIXn/SocketReader.cs [hunk 5]
```diff
@@ -200,6 +202,13 @@ protected void ProcessStream()
 
         protected void DisconnectClient()
         {
+            _readCancellationTokenSource.Cancel();
```
Comment (Rob-Hague) [inline QuickFIXn/SocketReader.cs:205]: It feels like these lines should be in `Dispose` and `DisconnectClient` should just call `Dispose`

**Review by Rob-Hague — COMMENTED** [review]
The nullable changes look good. I've left a few comments on SocketReader, although they mostly pertain to the original PR. TBH the benefit/risk ratio on this PR doesn't feel super high

File: QuickFIXn/SocketReader.cs (hunk 2 above)
Comment (gbirchmeier) [reply QuickFIXn/SocketReader.cs:90]: I'm realizing now that I could just call `request.Dispose()` after `request.Result`.

But of course, if I don't need to Dispose at all, then I won't.

File: QuickFIXn/SocketReader.cs (hunk 4 above)
Comment (gbirchmeier) [reply QuickFIXn/SocketReader.cs:115]: not a bad idea, but I think I'll leave it as-is

**Comment by gbirchmeier** [comment]
I made those changes.

I have also nullable-ized and cleaned up SocketInitiatorThread, and also replicated the similar changes in that file.  All tests appear passing, and I would again appreciate a pair of eyes to review these changes.

File: QuickFIXn/SocketInitiatorThread.cs [hunk 6]
```diff
@@ -129,75 +114,84 @@ public bool Read()
...
+
+                return 0;
             }
-            catch (System.IO.IOException ex) // Timeout
+            catch (AggregateException ex) // Timeout
             {
-                var inner = ex.InnerException as SocketException;
-                if (inner != null && inner.SocketErrorCode == SocketError.TimedOut)
-                {
+                var ioException = ex.InnerException as IOException;
```
Comment (Rob-Hague) [inline QuickFIXn/SocketInitiatorThread.cs:148]:
```suggestion
                _currentReadTask = null;
                
                var ioException = ex.InnerException as IOException;
```

**Review by Rob-Hague — APPROVED** [review]
Looks good to me

File: QuickFIXn/SocketInitiatorThread.cs (hunk 6 above)
Comment (gbirchmeier) [reply QuickFIXn/SocketInitiatorThread.cs:148]: good catch
