### PR TITLE
fix DefaultMessageFactory thread-race issue

### LINKED ISSUE #864: Timing issue loading DLLs
There is a potential timing issue if you start more than one connection at the same time, each creating a DefaultMessageFactory.

When discovering the QuickFix.FIXxx.dll libraries, LoadLocalDlls() kicks out the second (and any subsequent) thread to prevent it reloading the same assemblies into memory. But if the first thread has not finished iterating through all the libraries and exited the function, the second thread will end up querying a truncated list and won't have all the factories in its list. That leads to an incorrect BeginString error at runtime when parsing message groups (and took a load of tracking down).

Better to lock the DefaultMessageFactory.LoadLocalDlls() function to ensure it completes before the second thread hits the loadFlag test.

### PR DESCRIPTION
**Pull request by gbirchmeier**
When multiple threads race to init `DefaultMessageFactory`, fix it so that later threads do not return before the first thread finishes loading all the dlls.

resolves #864 

attn @baffled

### CODE REVIEW

File: QuickFIXn/DefaultMessageFactory.cs [hunk 1]
```diff
@@ -119,41 +116,42 @@ public Group Create(string beginString, string msgType, int groupCounterTag)
...
+                    if (String.IsNullOrWhiteSpace(directory))
+                        return;
+
+                    var dlls = Directory.GetFiles(directory, "QuickFix.*.dll");
+                    foreach (var path in dlls)
+                        Assembly.LoadFrom(path);
 
-                var dlls = Directory.GetFiles(directory, "QuickFix.*.dll");
-                foreach (var path in dlls)
+                    _dllsAreLoaded = true;
```
Comment (Rob-Hague) [inline QuickFIXn/DefaultMessageFactory.cs:147]: I think for ultimate thread safety, either `_dllsAreLoaded` needs to be marked with `volatile` or the first `if` outside of the lock needs to be removed (easiest to reason about). I think otherwise there is nothing theoretically preventing this write being executed out of order and becoming observable (by another thread outside the lock) before the preceding code has finished.

Pretty theoretical and I may be wrong as to whether that can actually happen

Comment (gbirchmeier) [reply QuickFIXn/DefaultMessageFactory.cs:147]: I think you're right that `volatile` is probably appropriate.

I was about to argue in favor of leaving the `if` in, but I realized that this function won't be called enough for that to cause any actual efficiency gain.  Not sure why I didn't realize that when I wrote it.

**Comment by gbirchmeier** [comment]
Was hoping @baffled would take a look, but I guess he's not going to.  Time to merge...

**Comment by gbirchmeier** [comment]
@Rob-Hague I made the fix to remove the first "if".  With that, the "volatile" modifier is probably not needed (which you kind of implied with your comment).

**Comment by Rob-Hague** [comment]
Agreed, volatile not needed, looks good to me
